import type { Metadata } from "next";
import { ArrowUpRight, Check } from "lucide-react";
import Link from "next/link";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Reveal } from "@/components/Reveal";
import { AiSearchAnalytics, AiSearchContactLink } from "@/components/AiSearchAnalytics";
import { getRequestLocale } from "@/lib/locale-server";
import { SITE_URL } from "@/lib/seo";

export const metadata: Metadata = {
  title: "AI Search & Visibility | Hospo Creative",
  description: "SEO, AEO, GEO e ChatGPT Ads para hotéis, alojamentos e restaurantes: uma presença digital mais clara para a evolução da pesquisa.",
  alternates: { canonical: `${SITE_URL}/pt/ai-search` },
  openGraph: { title: "AI Search & Visibility | Hospo Creative", description: "Preparar a presença digital de hotéis, alojamentos e restaurantes para a nova forma como os clientes pesquisam.", url: `${SITE_URL}/pt/ai-search`, locale: "pt_PT" }
};

const pillars = [
  ["SEO", "Ser encontrado nos motores de pesquisa", "Trabalhamos a estrutura, conteúdo e presença digital do website para melhorar a visibilidade em pesquisas relevantes para o negócio.", ["Pesquisa de palavras e intenções", "Otimização de páginas e estrutura do website", "SEO local, metadados, indexação e conteúdo", "Performance técnica quando aplicável"]],
  ["AEO", "Responder melhor às perguntas dos clientes", "AEO significa Answer Engine Optimisation. Ajuda a organizar o conteúdo para responder de forma clara às perguntas que potenciais clientes fazem online.", ["Localização, estacionamento e horários", "Tipos de quarto, serviços, spa e pequeno-almoço", "Menus, opções vegetarianas, grupos e eventos", "Experiências e informações úteis antes da escolha"]],
  ["GEO", "Preparar a informação da marca para ferramentas de IA", "GEO significa Generative Engine Optimisation. Trabalha a forma como a informação sobre o negócio está estruturada e apresentada online, ajudando plataformas baseadas em Inteligência Artificial a compreender melhor a marca, localização, oferta e diferenciação.", ["Informação clara e consistente", "Estrutura e contexto da oferta", "Sinais digitais que facilitam a compreensão da marca"]],
  ["ChatGPT Ads", "Publicidade em novos ambientes de pesquisa", "A pesquisa assistida por IA também está a criar novos espaços publicitários. A HOSPO pode apoiar campanhas em ChatGPT Ads quando este canal for adequado aos objetivos do negócio.", ["Estratégia e configuração", "Segmentação disponível", "Criativos e copy", "Otimização, acompanhamento e reporting"]]
] as const;

const faqs = [
  ["O que é AEO?", "AEO significa Answer Engine Optimisation. Consiste em organizar conteúdo para responder de forma mais clara às perguntas que os utilizadores fazem nos motores de pesquisa e outras plataformas."],
  ["O que é GEO?", "GEO significa Generative Engine Optimisation. Trabalha a forma como a informação sobre uma marca é apresentada online para facilitar a sua compreensão por plataformas de Inteligência Artificial."],
  ["Conseguem garantir que o meu hotel ou restaurante aparece no ChatGPT?", "Não. Nenhuma agência pode garantir que uma plataforma de Inteligência Artificial escolha ou recomende uma determinada marca. Podemos melhorar a estrutura, qualidade e consistência da presença digital para aumentar a capacidade de a marca ser encontrada e compreendida."],
  ["SEO continua a ser importante?", "Sim. SEO continua a ser uma parte essencial da descoberta digital. AEO e GEO complementam esse trabalho à medida que a forma como as pessoas pesquisam evolui."],
  ["ChatGPT Ads é o mesmo que aparecer organicamente no ChatGPT?", "Não. ChatGPT Ads é publicidade paga. SEO, AEO e GEO trabalham a presença e visibilidade orgânica da marca. São áreas diferentes e devem ser tratadas separadamente."]
] as const;

export default async function AiSearchPage() {
  const locale = await getRequestLocale();
  return <><Header locale={locale}/><AiSearchAnalytics/><main id="main" className="bg-white text-ink"><section className="bg-ink px-5 py-14 text-white sm:px-8 lg:py-20"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-yellow">AI Search &amp; Visibility</p><h1 className="mt-5 max-w-5xl font-serif text-[clamp(2.8rem,5.4vw,5rem)] leading-[0.94]">Prepare a sua marca para a nova forma como os clientes pesquisam.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-white/78">Os clientes já não descobrem hotéis e restaurantes apenas através de pesquisas tradicionais. Cada vez mais fazem perguntas completas, procuram recomendações e utilizam ferramentas de Inteligência Artificial para decidir onde ficar, onde comer e o que fazer.</p><p className="mt-5 max-w-3xl text-base leading-7 text-white/62">Ajudamos a estruturar a presença digital da sua marca para que seja mais fácil de encontrar, compreender e apresentar nos diferentes ambientes de pesquisa.</p><AiSearchContactLink className="button-primary mt-8"/></div></section>
  <section className="px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.8fr_1.2fr]"><Reveal><p className="section-eyebrow text-yellow">A mudança</p><h2 className="mt-5 font-serif text-[clamp(2.35rem,4.2vw,4rem)] leading-[0.95]">A pesquisa está a tornar-se mais conversacional.</h2></Reveal><Reveal delay={0.08}><p className="text-lg leading-8 text-ink/74">As pessoas já não pesquisam apenas “hotel Lisboa” ou “restaurante Algarve”. Fazem perguntas como “Qual é um bom hotel em Lisboa para um fim de semana romântico?” ou “Onde posso jantar no Algarve com vista para o mar?”.</p><p className="mt-5 text-base leading-7 text-ink/65">Trabalhamos a informação digital para que esteja clara, estruturada e relevante para este tipo de descoberta. Não controlamos as respostas de plataformas de IA.</p></Reveal></div></section>
  <section className="bg-[#f6f8fb] px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-yellow">O que fazemos</p><h2 className="mt-5 max-w-3xl font-serif text-[clamp(2.35rem,4.2vw,4rem)] leading-[0.95]">Uma presença mais clara para a pesquisa de hoje.</h2><div className="mt-10 grid gap-4 md:grid-cols-2">{pillars.map(([tag, title, body, items], index) => <Reveal key={tag} delay={index * .05} className="rounded-[8px] border border-ink/12 bg-white p-6 sm:p-7"><p className="section-eyebrow text-yellow">{tag}</p><h3 className="mt-4 font-serif text-3xl leading-[0.98]">{title}</h3><p className="mt-4 text-sm leading-7 text-ink/70">{body}</p><ul className="mt-5 space-y-2 border-t border-ink/10 pt-5">{items.map((item) => <li key={item} className="flex gap-2 text-sm leading-6 text-ink/70"><Check size={15} className="mt-1 shrink-0 text-yellow"/>{item}</li>)}</ul>{tag === "GEO" ? <p className="mt-5 border-l-2 border-yellow bg-yellow/10 p-4 text-sm leading-6 text-ink/76">Não é possível garantir que uma plataforma de IA escolha ou recomende uma determinada marca. O nosso trabalho consiste em melhorar os sinais digitais que ajudam estas plataformas a compreender o negócio.</p> : null}{tag === "ChatGPT Ads" ? <p className="mt-5 text-sm leading-6 text-ink/58">Disponibilidade, formatos e funcionalidades sujeitos à evolução da plataforma.</p> : null}</Reveal>)}</div><p className="mt-8 text-sm leading-7 text-ink/62"><strong className="text-ink">SEO + AEO + GEO</strong> trabalham a visibilidade orgânica. <strong className="text-ink">ChatGPT Ads</strong> é publicidade paga e uma área distinta.</p></div></section>
  <section className="bg-ink px-5 py-[var(--hc-section-compact)] text-white sm:px-8"><div className="mx-auto max-w-7xl grid gap-10 lg:grid-cols-2"><Reveal><p className="section-eyebrow text-yellow">Hotéis e alojamentos</p><h2 className="mt-5 font-serif text-[clamp(2.3rem,4vw,3.7rem)] leading-[.96]">Porque é especialmente relevante para hotéis e alojamentos</h2><p className="mt-5 text-base leading-7 text-white/72">Os clientes procuram por localização, tipo de viagem, quartos, amenities, restaurantes, spa, piscina, família, casais, negócios, eventos, MICE, experiências, atrações e transportes.</p><p className="mt-5 border-l-2 border-yellow pl-4 text-sm leading-7 text-white/65">Uma pessoa pode perguntar: “Qual é um boutique hotel em Lisboa para um fim de semana romântico, perto de bons restaurantes e onde possa fazer tudo a pé?”</p></Reveal><Reveal delay={.08}><p className="section-eyebrow text-yellow">Restaurantes</p><h2 className="mt-5 font-serif text-[clamp(2.3rem,4vw,3.7rem)] leading-[.96]">E para restaurantes?</h2><p className="mt-5 text-base leading-7 text-white/72">As pesquisas podem incluir tipo de cozinha, localização, ocasião, ambiente, vista, grupos, menus, opções vegetarianas ou halal, cocktails, brunch, jantar romântico, aniversários, eventos e experiências locais.</p><p className="mt-5 border-l-2 border-yellow pl-4 text-sm leading-7 text-white/65">“Qual é um bom restaurante português em Lisboa para um jantar especial?” A informação digital precisa de ajudar o negócio a ser relevante neste tipo de pesquisa.</p></Reveal></div></section>
  <section className="px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-yellow">Uma abordagem integrada</p><h2 className="mt-5 max-w-4xl font-serif text-[clamp(2.4rem,4.4vw,4.1rem)] leading-[.96]">Não tratamos a IA como um canal isolado.</h2><p className="mt-6 max-w-3xl text-lg leading-8 text-ink/74">A visibilidade em pesquisa depende de elementos que já fazem parte da presença digital de uma marca: website, conteúdo, SEO, localização, informação sobre produtos e serviços, reputação, dados estruturados e consistência entre plataformas.</p><p className="mt-5 max-w-3xl text-base leading-7 text-ink/65">Por isso, ligamos AI Search &amp; Visibility à estratégia digital existente do hotel ou restaurante, em vez de tratar a Inteligência Artificial como uma iniciativa separada.</p></div></section>
  <section className="bg-[#06396d] px-5 py-[var(--hc-section-compact)] text-white sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-yellow">Processo</p><div className="relative mt-9"><div className="absolute left-4 right-4 top-5 hidden h-px bg-yellow/70 lg:block"/><ol className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{[["01","Análise","Avaliamos como a marca está atualmente representada online e identificamos oportunidades."],["02","Estrutura","Organizamos e otimizamos a informação, conteúdo e presença digital."],["03","Implementação","Executamos as melhorias prioritárias no website e nos canais relevantes."],["04","Monitorização","Acompanhamos a evolução da pesquisa, comportamento dos utilizadores e novas oportunidades."]].map(([number,title,body]) => <li key={number} className="relative"><span className="relative z-10 flex size-10 items-center justify-center rounded-full border-2 border-yellow bg-[#06396d] text-xs font-black text-yellow">{number}</span><h3 className="mt-5 font-serif text-3xl">{title}</h3><p className="mt-3 text-sm leading-7 text-white/70">{body}</p></li>)}</ol></div></div></section>
  <section className="bg-white px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.65fr_1.35fr]"><div><p className="section-eyebrow text-yellow">FAQ</p><h2 className="mt-5 font-serif text-[clamp(2.3rem,4vw,3.8rem)] leading-[.96]">Perguntas práticas.</h2></div><div className="border-y border-ink/15">{faqs.map(([question,answer]) => <details key={question} className="group border-b border-ink/15 py-5 last:border-b-0"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-base font-bold leading-7"><span>{question}</span><span className="text-yellow transition group-open:rotate-45">+</span></summary><p className="pt-3 text-sm leading-7 text-ink/70">{answer}</p></details>)}</div></div></section>
  <section className="bg-ink px-5 py-16 text-white sm:px-8 sm:py-20"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="section-eyebrow text-yellow">Próximo passo</p><h2 className="mt-5 max-w-3xl font-serif text-[clamp(2.5rem,4.5vw,4.4rem)] leading-[.94]">A sua marca está preparada para a forma como os clientes pesquisam hoje?</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-white/72">Podemos analisar a presença digital do seu hotel ou restaurante e identificar onde existem oportunidades de melhoria.</p></div><AiSearchContactLink className="button-primary shrink-0"/></div></section></main><Footer locale={locale}/></>;
}
