import { Plus, Search } from "lucide-react";
import Link from "next/link";
import { BUSINESS_TYPES, LEAD_FITS, MARKETS, PIPELINE_STATUSES, PRIORITIES, formatLeadFit } from "@/lib/prospecting";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Prospect = { id: string; name: string; business_type: string; location: string | null; market: string; opportunity_score: number | null; priority: string; primary_service: string | null; lead_fit: string; pipeline_status: string; next_followup_at: string | null; owner: { full_name: string | null; email: string } | null; created_at: string };
const chip = (value: string) => ({ HOT: "bg-red-100 text-red-800", WARM: "bg-yellow text-ink", WATCH: "bg-sky-100 text-sky-900", LOW: "bg-ink/10 text-ink" } as Record<string, string>)[value] ?? "bg-ink/10 text-ink";
const date = (value: string | null) => value ? new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value)) : "Not scheduled";

export default async function ProspectsPage({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const params = await searchParams; const supabase = await createSupabaseServerClient();
  let query = supabase.from("prospects").select("id,name,business_type,location,market,opportunity_score,priority,primary_service,lead_fit,pipeline_status,next_followup_at,created_at,owner:profiles!prospects_owner_user_id_fkey(full_name,email)").order("opportunity_score", { ascending: false, nullsFirst: false }).order("updated_at", { ascending: false });
  (["business_type", "market", "lead_fit", "priority", "pipeline_status", "primary_service"] as const).forEach((field) => { if (params[field]) query = query.eq(field, params[field]!); });
  if (params.q) query = query.or(`name.ilike.%${params.q}%,location.ilike.%${params.q}%,website_url.ilike.%${params.q}%`);
  const { data, error } = await query; const prospects = (data ?? []) as unknown as Prospect[];
  const metric = (predicate: (item: Prospect) => boolean) => prospects.filter(predicate).length;
  const filter = (name: string, options: readonly string[], label: string) => <label className="text-xs font-black uppercase tracking-[0.12em] text-ink/50">{label}<select name={name} defaultValue={params[name] ?? ""} className="mt-1 block min-h-10 rounded-[8px] border border-ink/14 bg-white px-3 text-sm font-bold normal-case tracking-normal text-ink"><option value="">All</option>{options.map((option) => <option key={option} value={option}>{name === "lead_fit" ? formatLeadFit(option) : option}</option>)}</select></label>;
  return <div><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="section-eyebrow text-ink/55">Prospecting</p><h1 className="mt-3 font-serif text-5xl font-semibold leading-none">Prospects.</h1></div><Link href="/admin/prospects/new" className="inline-flex min-h-11 items-center gap-2 rounded-full bg-ink px-5 text-xs font-black uppercase tracking-[0.14em] text-white"><Plus size={16} />New prospect</Link></div>
    {error ? <p className="mt-6 rounded-[8px] border border-red-200 bg-red-50 p-4 text-sm font-bold text-red-800">{error.message}</p> : null}
    <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-8">{[["Total", prospects.length], ["HOT", metric((item) => item.priority === "HOT")], ["Ready", metric((item) => item.pipeline_status === "Ready for Outreach")], ["Contacted", metric((item) => item.pipeline_status === "Contacted")], ["Meetings", metric((item) => item.pipeline_status === "Meeting")], ["Proposals", metric((item) => item.pipeline_status === "Proposal")], ["Won", metric((item) => item.pipeline_status === "Won")], ["Overdue", metric((item) => Boolean(item.next_followup_at && new Date(item.next_followup_at) < new Date()))]].map(([label, count]) => <div key={String(label)} className="rounded-[8px] bg-white p-4 shadow-soft"><p className="text-[0.6rem] font-black uppercase tracking-[0.12em] text-ink/48">{label}</p><p className="mt-2 text-2xl font-black">{count}</p></div>)}</div>
    <form className="mt-7 flex flex-wrap items-end gap-3 rounded-[8px] bg-white p-4 shadow-soft"><label className="min-w-56 flex-1 text-xs font-black uppercase tracking-[0.12em] text-ink/50">Search business, location or website<div className="relative mt-1"><Search className="absolute left-3 top-3 text-ink/45" size={16}/><input name="q" defaultValue={params.q ?? ""} className="min-h-10 w-full rounded-[8px] border border-ink/14 pl-9 pr-3 text-sm" /></div></label>{filter("business_type", BUSINESS_TYPES, "Type")}{filter("market", MARKETS, "Market")}{filter("lead_fit", LEAD_FITS, "Fit")}{filter("priority", PRIORITIES, "Priority")}{filter("pipeline_status", PIPELINE_STATUSES, "Status")}<button className="min-h-10 rounded-full bg-ink px-4 text-xs font-black uppercase tracking-[0.12em] text-white">Filter</button><Link href="/admin/prospects" className="min-h-10 px-3 py-3 text-xs font-black uppercase tracking-[0.12em] text-ink/60">Clear</Link></form>
    <div className="mt-6 overflow-x-auto rounded-[8px] bg-white shadow-soft"><table className="min-w-[1050px] w-full text-left"><thead className="border-b border-ink/10 text-[0.62rem] font-black uppercase tracking-[0.12em] text-ink/48"><tr>{["Business", "Type", "Location", "Market", "Opportunity", "Priority", "Primary opportunity", "Lead Fit", "Status", "Next follow-up", "Owner"].map((heading) => <th key={heading} className="px-4 py-4">{heading}</th>)}</tr></thead><tbody>{prospects.map((prospect) => <tr key={prospect.id} className="border-b border-ink/8 hover:bg-yellow/10"><td className="px-4 py-4"><Link href={`/admin/prospects/${prospect.id}`} className="font-bold hover:text-yellow">{prospect.name}</Link></td><td className="px-4 py-4 text-sm text-ink/65">{prospect.business_type}</td><td className="px-4 py-4 text-sm text-ink/65">{prospect.location || "-"}</td><td className="px-4 py-4 text-sm">{prospect.market}</td><td className="px-4 py-4 font-black">{prospect.opportunity_score ?? "Incomplete"}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-[0.6rem] font-black tracking-[0.1em] ${chip(prospect.priority)}`}>{prospect.priority}</span></td><td className="px-4 py-4 text-sm">{prospect.primary_service || "-"}</td><td className="px-4 py-4"><span className="rounded-full bg-ink/8 px-2.5 py-1 text-xs font-bold">{prospect.lead_fit}</span></td><td className="px-4 py-4 text-sm">{prospect.pipeline_status}</td><td className="px-4 py-4 text-sm text-ink/65">{date(prospect.next_followup_at)}</td><td className="px-4 py-4 text-sm text-ink/65">{prospect.owner?.full_name || prospect.owner?.email || "-"}</td></tr>)}{!prospects.length ? <tr><td colSpan={11} className="px-6 py-14 text-center text-lg font-bold text-ink/60">No prospects match these filters.</td></tr> : null}</tbody></table></div>
  </div>;
}
