import Link from "next/link";
import { ArrowUpRight, Check } from "lucide-react";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { SectionHeading } from "@/components/SectionHeading";
import { displayPrice } from "@/lib/commercial";
import type { Locale } from "@/lib/i18n";
import type { CommercialItem } from "@/types/commercial";

type LandingCopy = {
  eyebrow: string; title: string; intro: string; whyTitle: string; why: string;
  problemTitle: string; problemItems: string[]; journeyTitle: string; packageTitle: string;
  packageBody: string; note: string; addOnTitle: string; cta: string; explore: string;
};

const copy: Record<"restaurant" | "hotel", Record<Locale, LandingCopy>> = {
  restaurant: {
    en: { eyebrow: "Hospo for restaurants & F&B", title: "Content people notice. Marketing that fills tables.", intro: "We help restaurants, bars and hospitality brands build stronger visibility, create content worth stopping for and turn attention into real customer demand.", whyTitle: "We know hospitality from the inside.", why: "We understand service, operations, guest expectations and the commercial pressure behind every busy Friday night and quiet Tuesday. That means we create work that does more than look good.", problemTitle: "Good food is not enough if nobody sees it.", problemItems: ["Great venue, inconsistent content", "Strong product, weak digital presence", "Social engagement without bookings", "No clear content strategy"], journeyTitle: "Content. Discovery. Demand.", packageTitle: "Choose the level of support your business needs.", packageBody: "No oversized retainers. No unnecessary services. Just the right level of creative and digital support for where your business is today.", note: "Paid media spend is always separate from Hospo management fees.", addOnTitle: "Add what you need. Not what you do not.", cta: "Talk to Hospo", explore: "Explore packages" },
    pt: { eyebrow: "Hospo para restaurantes e F&B", title: "Conteúdo que chama a atenção. Marketing que enche mesas.", intro: "Ajudamos restaurantes, bares e marcas de hotelaria a reforçar a visibilidade, criar conteúdo que merece ser visto e transformar atenção em procura real.", whyTitle: "Conhecemos a hotelaria por dentro.", why: "Compreendemos serviço, operações, expectativas dos clientes e a pressão comercial de uma sexta-feira cheia ou uma terça-feira calma. Por isso, criamos trabalho que faz mais do que ter bom aspeto.", problemTitle: "Boa comida não chega se ninguém a vê.", problemItems: ["Um espaço forte com conteúdo inconsistente", "Um produto forte com presença digital fraca", "Interação nas redes sem reservas", "Sem estratégia de conteúdo clara"], journeyTitle: "Conteúdo. Descoberta. Procura.", packageTitle: "Escolha o nível de apoio que o seu negócio precisa.", packageBody: "Sem avenças excessivas. Sem serviços desnecessários. Apenas o nível certo de apoio criativo e digital para o momento atual do seu negócio.", note: "O investimento em media pago é sempre separado dos honorários de gestão da Hospo.", addOnTitle: "Adicione o que precisa. Não o que não precisa.", cta: "Fale com a Hospo", explore: "Explorar packages" },
  },
  hotel: {
    en: { eyebrow: "Hospo for hotels & stays", title: "Show the experience. Strengthen demand.", intro: "We help independent hotels and stays connect the content guests see with the decisions that lead to direct bookings.", whyTitle: "We know hospitality from the inside.", why: "From rooms and facilities to seasonal offers and direct booking, we understand the operational details behind a guest choosing to stay.", problemTitle: "A good stay needs a clear reason to choose it.", problemItems: ["Strong property, dated visual library", "Inconsistent guest journey", "Visibility without direct demand", "Campaigns without a connected booking route"], journeyTitle: "Content. Discovery. Direct demand.", packageTitle: "Choose the level of support your property needs.", packageBody: "A clear commercial foundation, scaled to your team, property and direct booking goals.", note: "Media spend and third-party platform costs are separate.", addOnTitle: "Add focused support when it matters.", cta: "Talk to Hospo", explore: "Explore packages" },
    pt: { eyebrow: "Hospo para hotéis e estadias", title: "Mostre a experiência. Reforce a procura.", intro: "Ajudamos hotéis independentes e alojamentos a ligar o conteúdo que os hóspedes veem às decisões que conduzem a reservas diretas.", whyTitle: "Conhecemos a hotelaria por dentro.", why: "De quartos e instalações a ofertas sazonais e reservas diretas, compreendemos os detalhes operacionais que fazem um hóspede escolher ficar.", problemTitle: "Uma boa estadia precisa de uma razão clara para ser escolhida.", problemItems: ["Uma propriedade forte com biblioteca visual desatualizada", "Jornada do hóspede inconsistente", "Visibilidade sem procura direta", "Campanhas sem uma rota de reserva ligada"], journeyTitle: "Conteúdo. Descoberta. Procura direta.", packageTitle: "Escolha o nível de apoio que a sua propriedade precisa.", packageBody: "Uma base comercial clara, ajustada à sua equipa, propriedade e objetivos de reserva direta.", note: "O investimento em media e custos de plataformas de terceiros são separados.", addOnTitle: "Adicione apoio focado quando for importante.", cta: "Fale com a Hospo", explore: "Explorar packages" },
  },
};

function localized(item: CommercialItem, key: "name" | "description" | "included_items", locale: Locale) {
  const translated = key === "name" ? item.name_pt : key === "description" ? item.description_pt : item.included_items_pt;
  if (locale === "pt" && translated) return translated as string | string[];
  return item[key] as string | string[];
}

export function CommercialPackagesLanding({ market, locale, packages, addons }: { market: "restaurant" | "hotel"; locale: Locale; packages: CommercialItem[]; addons: CommercialItem[] }) {
  const content = copy[market][locale];
  const principles = locale === "pt" ? ["Experiência em hotelaria", "Produção criativa", "Pensamento comercial"] : ["Hospitality experience", "Creative production", "Commercial thinking"];
  const journey = locale === "pt" ? ["Conteúdo", "Descoberta", market === "hotel" ? "Reservas diretas" : "Reservas e visitas repetidas"] : ["Content", "Discovery", market === "hotel" ? "Direct bookings" : "Reservations & repeat visits"];
  return <><Header locale={locale} /><main>
    <section className="bg-ink pb-20 pt-28 text-white sm:pb-28 sm:pt-36"><div className="page-shell"><p className="section-eyebrow text-yellow">{content.eyebrow}</p><h1 className="mt-4 max-w-5xl font-serif text-[clamp(3.3rem,7vw,6.6rem)] font-semibold leading-[0.93] tracking-[-0.04em]">{content.title}</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-white/72">{content.intro}</p><div className="mt-9 flex flex-wrap gap-3"><a href="#packages" className="button-primary">{content.explore}<ArrowUpRight size={16} /></a><Link href={locale === "pt" ? "/pt/contact" : "/contact"} className="button-secondary border-white/35 text-white hover:border-yellow hover:text-yellow">{content.cta}<ArrowUpRight size={16} /></Link></div></div></section>
    <section className="section-pad"><div className="page-shell grid gap-12 lg:grid-cols-[0.85fr_1.15fr]"><SectionHeading eyebrow={content.eyebrow} title={content.whyTitle} body={content.why}/><div className="grid gap-3 sm:grid-cols-3">{principles.map((item, index) => <div key={item} className="rounded-[8px] bg-ink p-6 text-white"><p className="section-eyebrow text-yellow">0{index + 1}</p><p className="mt-12 font-serif text-3xl leading-tight">{item}</p></div>)}</div></div></section>
    <section className="section-pad bg-sand"><div className="page-shell"><SectionHeading eyebrow={content.eyebrow} title={content.problemTitle}/><div className="mt-10 grid gap-px overflow-hidden rounded-[8px] bg-ink/15 sm:grid-cols-2 lg:grid-cols-4">{content.problemItems.map((item) => <p key={item} className="bg-sand p-6 text-lg leading-7 text-ink/75">{item}</p>)}</div><div className="mt-14 rounded-[8px] bg-ink px-7 py-10 text-white sm:px-10"><p className="section-eyebrow text-yellow">{locale === "pt" ? "Jornada conectada" : "Connected journey"}</p><p className="mt-3 font-serif text-4xl">{content.journeyTitle}</p><div className="mt-9 grid gap-3 sm:grid-cols-3">{journey.map((item, index) => <div key={item} className="border-t border-white/20 pt-4"><span className="text-yellow">0{index + 1}</span><p className="mt-2 text-lg">{item}</p></div>)}</div></div></div></section>
    <section id="packages" className="section-pad"><div className="page-shell"><SectionHeading eyebrow={content.eyebrow} title={content.packageTitle} body={content.packageBody}/><p className="mt-5 text-sm leading-6 text-ink/55">{content.note}</p><div className="mt-12 grid gap-5 lg:grid-cols-3">{packages.map((item) => <article key={item.id} className={`flex flex-col rounded-[8px] border p-7 ${item.featured ? "border-ink bg-ink text-white" : "border-ink/15 bg-white text-ink"}`}><p className={`section-eyebrow ${item.featured ? "text-yellow" : "text-ink/55"}`}>{item.badge && locale === "en" ? item.badge : item.badge_pt || ""}</p><h2 className="mt-4 font-serif text-4xl leading-none">{localized(item, "name", locale) as string}</h2><p className={`mt-4 text-2xl font-bold ${item.featured ? "text-yellow" : "text-ink"}`}>{displayPrice(item, locale)}</p><p className={`mt-5 text-sm leading-6 ${item.featured ? "text-white/70" : "text-ink/67"}`}>{localized(item, "description", locale) as string}</p><ul className="mt-7 space-y-3">{(localized(item, "included_items", locale) as string[]).map((included) => <li key={included} className="flex gap-3 text-sm leading-6"><Check size={17} className="mt-0.5 shrink-0 text-yellow" />{included}</li>)}</ul><Link href={locale === "pt" ? "/pt/contact" : "/contact"} className={`mt-8 inline-flex items-center gap-2 text-[0.66rem] font-black uppercase tracking-[0.14em] ${item.featured ? "text-yellow" : "text-ink"}`}>{content.cta}<ArrowUpRight size={16}/></Link></article>)}</div></div></section>
    {addons.length ? <section className="section-pad bg-ink text-white"><div className="page-shell"><SectionHeading eyebrow={content.eyebrow} title={content.addOnTitle} tone="light"/><div className="mt-10 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{addons.map((item) => <div key={item.id} className="rounded-[8px] border border-white/20 p-5"><p className="font-serif text-2xl">{localized(item, "name", locale) as string}</p><p className="mt-2 text-yellow">{displayPrice(item, locale)}</p><p className="mt-3 text-sm leading-6 text-white/65">{localized(item, "description", locale) as string}</p></div>)}</div></div></section> : null}
  </main><Footer locale={locale} /></>;
}
