import Link from "next/link";
import { ArrowUpRight, Check } from "lucide-react";
import { contentCreationPackages } from "@/data/contentCreationLanding";
import { imageFolders, photoGalleryImageText } from "@/data/images";
import { displayPrice } from "@/lib/commercial";
import { getPublicImageList } from "@/lib/imageFolders";
import { MosaicGallery } from "./MosaicGallery";
import { Reveal } from "./Reveal";
import { SectionHeading } from "./SectionHeading";

export function PrivateContentCreationLanding() {
  const enquiryHref = "/contact?package=Content%20Plus";
  const galleryItems = getPublicImageList(imageFolders.photoGallery, {
    text: photoGalleryImageText,
    altPrefix: "Hospo Creative festive campaign image"
  }).map(({ src, alt }) => ({ src, alt }));

  return <article className="overflow-hidden rounded-[8px] border border-ink/10 bg-white shadow-soft">
    <section className="bg-ink px-5 py-14 text-white sm:px-8 sm:py-20"><Reveal className="mx-auto max-w-7xl"><p className="section-eyebrow text-yellow">Festive season content packages</p><h1 className="mt-5 max-w-5xl font-serif text-[clamp(2.9rem,6vw,5.5rem)] font-semibold leading-[.92]">Give guests a reason to choose your venue this festive season.</h1><p className="mt-7 max-w-3xl text-base leading-7 text-white/72 sm:text-lg sm:leading-8">Create the photography and short-form video that brings festive menus, celebrations, stays, events and the atmosphere of your venue to life across social media.</p><a href="#packages" className="button-primary mt-8 w-full sm:w-auto">Explore packages <ArrowUpRight size={16} /></a></Reveal></section>
    <section className="px-5 py-[var(--hc-section-compact)] text-ink sm:px-8"><div className="mx-auto max-w-7xl"><Reveal><SectionHeading eyebrow="Content creation" title="Choose the content coverage that fits your festive campaign." body="Each package is designed to give your venue a useful, platform-ready bank of visual content for the moments guests are planning where to celebrate."/></Reveal><div className="mt-12 grid gap-5 lg:grid-cols-3">{contentCreationPackages.map((item, index) => <Reveal key={item.id} delay={index * 0.09} className="h-full"><article className={`flex h-full flex-col rounded-[8px] border p-6 transition duration-300 hover:-translate-y-1 hover:shadow-lg sm:p-7 ${item.featured ? "border-ink bg-ink text-white lg:-translate-y-3 lg:py-9 lg:hover:-translate-y-4" : "border-ink/15 bg-white text-ink"}`}><p className={`section-eyebrow ${item.featured ? "text-yellow" : "text-ink/55"}`}>{item.badge || ""}</p><h2 className="mt-4 font-serif text-[2.1rem] leading-none sm:text-4xl">{item.name}</h2><p className={`mt-4 text-2xl font-bold ${item.featured ? "text-yellow" : "text-ink"}`}>{displayPrice(item)}</p><p className={`mt-5 min-h-[3rem] text-sm leading-6 ${item.featured ? "text-white/72" : "text-ink/67"}`}>{item.description}</p><ul className="mt-7 space-y-3">{item.included_items.map((included) => <li key={included} className={`flex gap-3 text-sm leading-6 ${item.featured ? "text-white/88" : "text-ink/80"}`}><Check size={17} className="mt-0.5 shrink-0 text-yellow"/>{included}</li>)}</ul><Link href={enquiryHref} className={`mt-8 inline-flex min-h-11 items-center gap-2 text-[0.66rem] font-black uppercase tracking-[0.14em] ${item.featured ? "text-yellow" : "text-ink"}`}>Plan Your Content Shoot <ArrowUpRight size={16}/></Link></article></Reveal>)}</div><Reveal delay={0.12}><p className="mt-10 max-w-5xl border-l-2 border-yellow pl-5 text-sm leading-7 text-ink/70">Every shoot is tailored to the business. Content can focus on areas such as food and drinks, rooms and interiors, products, services, team, atmosphere, guest experience, events or specific campaigns depending on what the client wants to promote.</p></Reveal></div></section>
    <section className="bg-ink px-5 py-[var(--hc-section-compact)] text-white sm:px-8"><div className="mx-auto max-w-7xl"><Reveal><SectionHeading eyebrow="Visual storytelling" title="Make the festive atmosphere easy to imagine." body="The strongest campaign content helps guests picture the occasion, from the first post they notice to the moment they book, reserve or enquire." tone="light"/></Reveal><MosaicGallery items={galleryItems} locale="en"/></div></section>
    <section className="bg-ink px-5 py-12 text-white sm:px-8"><Reveal className="mx-auto flex max-w-7xl flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="section-eyebrow text-yellow">Next step</p><h2 className="mt-3 max-w-3xl font-serif text-[clamp(2.2rem,4vw,3rem)] leading-tight">Plan a festive content shoot around what you want to promote.</h2></div><Link href={enquiryHref} className="button-primary w-full shrink-0 sm:w-auto">Plan Your Content Shoot <ArrowUpRight size={16}/></Link></Reveal></section>
  </article>;
}
