import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, Check, Download, Linkedin, Mail, MapPin } from "lucide-react";
import { imageFolders, photoGalleryImageText } from "@/data/images";
import { getPublicImageList } from "@/lib/imageFolders";
import { localizedPath, type Locale } from "@/lib/i18n";
import type { CaseStudy } from "@/types/caseStudy";

type Text = Record<string, string>;
const copy: Record<Locale, Text> = {
  en: {
    eyebrow: "Content creator · Photographer · Videographer", subhead: "Content creator, photographer and videographer specialising in hospitality, food and lifestyle.", body: "I plan, shoot and edit photography, video and social-first content for hotels, restaurants and brands, combining professional production with 15 years of hospitality experience and a strong understanding of digital marketing.", location: "Portugal & UK", availability: "Available for international projects", work: "View my work", cv: "Download CV", about: "About", aboutTitle: "Hospitality experience. Creative production. Digital thinking.", aboutBody: "I’m a photographer, videographer and content creator with a background spanning approximately 15 years in hospitality and F&B across Portugal and the UK. Today I combine that operational experience with professional visual production, creating photography, video and digital content for social media, websites, campaigns and commercial use.", hospo: "At Hospo Creative, which I co-founded in 2024, I lead photography, video, creative direction and business development across hospitality projects in the UK, Portugal and selected international markets.", selected: "Selected work", selectedTitle: "Projects that show the work, not just the client list.", selectedBody: "A selection of hotel, restaurant and hospitality projects where I have contributed to visual production through Hospo Creative.", contribution: "My contribution", view: "View project", capabilities: "What I do", capabilitiesTitle: "End-to-end content production, built for real use.", process: "Production process", processTitle: "More than taking pictures.", results: "Content & results", resultsTitle: "Content as part of a wider commercial programme.", resultsBody: "For Beleza Rodizio, I produced social-first photography and video as part of an integrated HOSPO content and marketing programme. The account grew from approximately 1K to 13.5K Instagram followers in under a year; one reporting month reached more than 460K people. These results reflect the combined work across content, social management, campaigns and collaborations.", experience: "Experience", experienceTitle: "A creative career grounded in hospitality operations.", skills: "Skills & tools", skillsTitle: "Creative, technical and commercially aware.", development: "Professional development", testimonials: "What clients say", testimonialsTitle: "Feedback on the work delivered.", connect: "Let’s connect", connectTitle: "Looking for someone who can plan, shoot and deliver content?", connectBody: "I’m open to content, photography, video and hospitality marketing opportunities across Portugal, the UK and selected international projects.", email: "Email me"
  },
  pt: {
    eyebrow: "Criador de conteúdo · Fotógrafo · Videógrafo", subhead: "Criador de conteúdo, fotógrafo e videógrafo especializado em hotelaria, gastronomia e lifestyle.", body: "Planeio, fotografo e edito fotografia, vídeo e conteúdo pensado para redes sociais para hotéis, restaurantes e marcas, combinando produção profissional com 15 anos de experiência em hotelaria e um conhecimento sólido de marketing digital.", location: "Portugal e Reino Unido", availability: "Disponível para projetos internacionais", work: "Ver projetos", cv: "Descarregar CV", about: "Sobre mim", aboutTitle: "Experiência em hotelaria. Produção criativa. Pensamento digital.", aboutBody: "Sou fotógrafo, videógrafo e criador de conteúdo, com um percurso de aproximadamente 15 anos em hotelaria e F&B, entre Portugal e o Reino Unido. Atualmente junto essa experiência operacional à produção visual profissional, criando fotografia, vídeo e conteúdo digital para redes sociais, websites, campanhas e utilização comercial.", hospo: "Na Hospo Creative, que cofundei em 2024, lidero fotografia, vídeo, direção criativa e desenvolvimento de negócio em projetos de hotelaria no Reino Unido, em Portugal e em mercados internacionais selecionados.", selected: "Projetos selecionados", selectedTitle: "Projetos que mostram o trabalho, não apenas a lista de clientes.", selectedBody: "Uma seleção de projetos de hotelaria e restauração nos quais contribuí para a produção visual através da Hospo Creative.", contribution: "A minha contribuição", view: "Ver projeto", capabilities: "O que faço", capabilitiesTitle: "Produção de conteúdo de ponta a ponta, pensada para utilização real.", process: "Processo de produção", processTitle: "Mais do que tirar fotografias.", results: "Conteúdo e resultados", resultsTitle: "Conteúdo integrado num programa comercial mais amplo.", resultsBody: "Para a Beleza Rodizio, produzi fotografia e vídeo pensados para redes sociais como parte de um programa integrado de conteúdo e marketing da HOSPO. A conta cresceu de aproximadamente 1K para 13,5K seguidores no Instagram em menos de um ano; num mês de reporte, alcançou mais de 460 mil pessoas. Estes resultados refletem o trabalho conjunto de conteúdo, gestão de redes sociais, campanhas e colaborações.", experience: "Experiência", experienceTitle: "Uma carreira criativa assente em operações de hotelaria.", skills: "Competências e ferramentas", skillsTitle: "Criativo, técnico e comercialmente consciente.", development: "Formação profissional", testimonials: "O que dizem os clientes", testimonialsTitle: "Feedback sobre o trabalho entregue.", connect: "Vamos falar", connectTitle: "Procura alguém que planeie, produza e entregue conteúdo?", connectBody: "Estou disponível para oportunidades de conteúdo, fotografia, vídeo e marketing para hotelaria em Portugal, no Reino Unido e em projetos internacionais selecionados.", email: "Enviar email"
  }
};

const capability: Record<Locale, Array<[string, string, string]>> = {
  en: [["01", "Photography", "Hospitality, food & beverage, interiors, lifestyle, people, events and campaign imagery."], ["02", "Video & short-form content", "Reels, TikTok, social-first video, experience films, campaign assets and vertical content."], ["03", "Content production", "Creative concepts, briefing, shot lists, production planning, styling direction, talent guidance and on-location production."], ["04", "Post-production", "Photo selection, retouching, colour grading, video editing and platform-ready delivery."], ["05", "Social & digital content", "Content planned for Instagram, TikTok, websites, paid campaigns, listings and digital channels."], ["06", "Content strategy", "Understanding the objective, audience and channel before production so the work has a clear commercial role."]],
  pt: [["01", "Fotografia", "Hotelaria, alimentação e bebidas, interiores, lifestyle, pessoas, eventos e imagem de campanha."], ["02", "Vídeo e conteúdo de curta duração", "Reels, TikTok, vídeo pensado para redes sociais, filmes de experiência, materiais de campanha e conteúdo vertical."], ["03", "Produção de conteúdo", "Conceitos criativos, briefing, listas de captação, planeamento de produção, direção de styling, orientação de talento e produção no local."], ["04", "Pós-produção", "Seleção de fotografia, retoque, gradação de cor, edição de vídeo e entrega preparada para cada plataforma."], ["05", "Conteúdo social e digital", "Conteúdo planeado para Instagram, TikTok, websites, campanhas pagas, listings e canais digitais."], ["06", "Estratégia de conteúdo", "Compreender o objetivo, audiência e canal antes da produção, para que o trabalho tenha uma função comercial clara."]]
};
const production: Record<Locale, Array<[string, string, string]>> = {
  en: [["01", "Brief", "Understand the objective, audience, channels and deliverables."], ["02", "Plan", "Build the shot list, schedule, styling direction and practical production plan."], ["03", "Produce", "Capture photography and video with the intended platform and commercial use in mind."], ["04", "Edit & deliver", "Select, retouch, edit, colour grade and prepare assets for the required channels."]],
  pt: [["01", "Briefing", "Compreender o objetivo, a audiência, os canais e os materiais a entregar."], ["02", "Planear", "Construir a lista de captação, o calendário, a direção de styling e o plano prático de produção."], ["03", "Produzir", "Captar fotografia e vídeo tendo em conta a plataforma e a utilização comercial prevista."], ["04", "Editar e entregar", "Selecionar, retocar, editar, fazer a gradação de cor e preparar materiais para os canais necessários."]]
};
const details: Record<string, Record<Locale, [string, string]>> = {
  "pan-pacific-hanoi": { en: ["Photography · Video · Hospitality content", "Photography and video content capturing the atmosphere and culinary highlights of Pan Pacific Hanoi."], pt: ["Fotografia · Vídeo · Conteúdo para hotelaria", "Conteúdo de fotografia e vídeo que capta a atmosfera e os destaques gastronómicos do Pan Pacific Hanoi."] },
  "pullman-danang-beach-resort": { en: ["Creative direction · Photography · Video", "Photography and video production for the relaunch of the resort’s liquid-nitrogen ice-cream experience, with lifestyle and resort imagery captured across the property."], pt: ["Direção criativa · Fotografia · Vídeo", "Produção de fotografia e vídeo para o relançamento da experiência de gelado de nitrogénio do resort, complementada por imagens de lifestyle e do espaço."] },
  "yotel-porto": { en: ["Photography · Video · Creative direction", "A complete visual production across rooms, technology, facilities, breakfast, food offering and lifestyle moments."], pt: ["Fotografia · Vídeo · Direção criativa", "Uma produção visual completa que abrange quartos, tecnologia, instalações, pequeno-almoço, oferta gastronómica e momentos de lifestyle."] },
  "ashas-award-winning-restaurant": { en: ["Food photography · Video · Social content", "Ongoing photography and video supporting seasonal menus, new dishes, cocktail launches and campaign content."], pt: ["Fotografia de gastronomia · Vídeo · Conteúdo para redes sociais", "Fotografia e vídeo contínuos para menus sazonais, novos pratos, lançamentos de cocktails e conteúdo de campanha."] },
  "beleza-rodizio-instagram-growth": { en: ["Photography · Video · Content production", "Social-first visual content produced as part of a multi-location content and marketing programme."], pt: ["Fotografia · Vídeo · Produção de conteúdo", "Conteúdo visual pensado para redes sociais, produzido como parte de um programa de conteúdo e marketing para várias localizações."] },
  "grand-tourane-hotel": { en: ["Photography · Video · Lifestyle content", "Guest-experience-led photography and video focused on the spa, outdoor areas and key hotel spaces."], pt: ["Fotografia · Vídeo · Conteúdo de lifestyle", "Fotografia e vídeo centrados na experiência do hóspede, com foco no spa, zonas exteriores e espaços-chave do hotel."] }
};
const preferred = ["pan pacific", "pullman-danang-beach-resort", "yotel-porto", "ashas-award-winning-restaurant", "beleza-rodizio-instagram-growth", "grand-tourane-hotel"];
const work: Record<Locale, Array<[string, string, string, string]>> = {
  en: [["2024–Present", "HOSPO Creative", "Co-Founder · Creative & Business Development Director · Photographer / Content Creator", "Lead photography, video, creative direction and business development. I manage productions from brief and shot planning through editing, colour grading and delivery."], ["2022–2026", "Orelle / The Evolv Collection", "Bar Manager", "Luxury hospitality operations and guest experience in Birmingham."], ["2022", "The Grand Hotel Birmingham", "Assistant Bar Manager", "Premium hotel operations, team support and guest experience."], ["2020–2022", "The Edgbaston Boutique Hotel & Cocktail Lounge", "Assistant Bar Manager / Bar Manager", "Hotel and cocktail-bar operations, team leadership and service delivery."], ["2016–2020", "VILA VITA Parc Resort & Spa", "Head Bartender", "Five-star resort, luxury events and fine-dining service, including a two-Michelin-star restaurant environment."], ["2019", "Bacardi Martini Portugal", "Brand Activator", "Brand activation, consumer engagement, campaign objectives and reporting."], ["2014–2016", "Tivoli / Meliá", "Hospitality operations", "Early experience across hotel and food and beverage operations in Portugal."]],
  pt: [["2024–Presente", "HOSPO Creative", "Cofundador · Diretor de Criação e Desenvolvimento de Negócio · Fotógrafo / Criador de Conteúdo", "Lidero fotografia, vídeo, direção criativa e desenvolvimento de negócio. Acompanho as produções desde o briefing e planeamento até à edição, gradação de cor e entrega."], ["2022–2026", "Orelle / The Evolv Collection", "Bar Manager", "Operações de hotelaria de luxo e experiência do cliente em Birmingham."], ["2022", "The Grand Hotel Birmingham", "Assistant Bar Manager", "Operações hoteleiras premium, apoio à equipa e experiência do cliente."], ["2020–2022", "The Edgbaston Boutique Hotel & Cocktail Lounge", "Assistant Bar Manager / Bar Manager", "Operações de hotel e cocktail bar, liderança de equipa e serviço."], ["2016–2020", "VILA VITA Parc Resort & Spa", "Head Bartender", "Resort de cinco estrelas, eventos de luxo e serviço de fine dining, incluindo contacto com um ambiente de restaurante com duas estrelas Michelin."], ["2019", "Bacardi Martini Portugal", "Brand Activator", "Ativação de marca, envolvimento do consumidor, objetivos de campanha e reporte."], ["2014–2016", "Tivoli / Meliá", "Operações de hotelaria", "Experiência inicial em operações hoteleiras e de alimentação e bebidas em Portugal."]]
};
const skills: Record<Locale, Array<[string, string[]]>> = {
  en: [["Creative", ["Photography", "Videography", "Short-form video", "Food & beverage photography", "Hospitality & interior photography", "Lifestyle photography", "Visual storytelling", "Creative direction"]], ["Content", ["Content creation", "Social-first content", "Reels & TikTok", "Content planning", "Shot lists", "Campaign content", "Brand content"]], ["Post-production", ["Adobe Lightroom", "Adobe Photoshop", "Adobe Premiere Pro", "CapCut", "Photo retouching", "Video editing", "Colour grading"]], ["Marketing & commercial", ["Hospitality marketing", "Digital marketing", "Social media", "Content strategy", "Business development", "Client management", "Campaign planning", "Performance analysis"]], ["Production", ["Sony full-frame systems", "Professional lighting", "Drone", "Gimbal", "On-location production", "Production coordination"]]],
  pt: [["Criativo", ["Fotografia", "Videografia", "Vídeo de curta duração", "Fotografia de alimentação e bebidas", "Fotografia de hotelaria e interiores", "Fotografia de lifestyle", "Narrativa visual", "Direção criativa"]], ["Conteúdo", ["Criação de conteúdo", "Conteúdo pensado para redes sociais", "Reels e TikTok", "Planeamento de conteúdo", "Listas de captação", "Conteúdo de campanha", "Conteúdo de marca"]], ["Pós-produção", ["Adobe Lightroom", "Adobe Photoshop", "Adobe Premiere Pro", "CapCut", "Retoque fotográfico", "Edição de vídeo", "Gradação de cor"]], ["Marketing e comercial", ["Marketing para hotelaria", "Marketing digital", "Redes sociais", "Estratégia de conteúdo", "Desenvolvimento de negócio", "Gestão de clientes", "Planeamento de campanhas", "Análise de desempenho"]], ["Produção", ["Sistemas Sony full-frame", "Iluminação profissional", "Drone", "Gimbal", "Produção no local", "Coordenação de produção"]]]
};
const courses = ["AI Generativa para Profissionais do Turismo | Turismo de Portugal / NEST | 2026", "Going Digital: Marketing Digital para o Setor do Turismo | Turismo de Portugal / NEST | 2026", "The Fundamentals of Digital Marketing | Google Digital Garage / The Open University | 2023", "Branding Estratégico | Turismo de Portugal | 2022", "Técnicas de Marketing Digital Avançado: E-commerce, Publicidade e Retargeting | Turismo de Portugal | 2021", "Ferramentas de controlo de gestão | Turismo de Portugal | 2021", "Digital Marketing | IEFP Portugal | 2020"];
const feedback: Record<Locale, Array<[string, string]>> = {
  en: [["We have reviewed all of the deliverables, and they are truly eye-catching. We especially love the way you captured our Afternoon Tea set and the Nitrogen Ice Cream Show.", "Marketing Communications Manager, Pullman Danang Beach Resort, Accor Hotels"], ["The final result from the YOTEL Porto photoshoot looks fantastic. We’re really pleased with the images and will be sharing them with our social media team to use across our digital channels.", "Influencer Marketing Consultant, M Public Relations"], ["Great results and great photos. We were really pleased with the final outcome and the quality of the content delivered for Asha’s Birmingham.", "Director, Asha’s Birmingham"]],
  pt: [["Revimos todos os materiais entregues e estão realmente apelativos. Gostamos especialmente da forma como captou o nosso conjunto de Chá da Tarde e o espetáculo de gelado de nitrogénio.", "Gestora de Comunicação de Marketing, Pullman Danang Beach Resort, Accor Hotels"], ["O resultado final da sessão fotográfica do YOTEL Porto está fantástico. Estamos muito satisfeitos com as imagens e vamos partilhá-las com a nossa equipa de redes sociais para as utilizar nos nossos canais digitais.", "Consultor de Marketing de Influência, M Public Relations"], ["Excelentes resultados e excelentes fotografias. Ficámos muito satisfeitos com o resultado final e com a qualidade do conteúdo entregue para o Asha’s Birmingham.", "Diretor, Asha’s Birmingham"]]
};

export function TiagoBastosProfile({ locale, caseStudies }: { locale: Locale; caseStudies: CaseStudy[] }) {
  const t = copy[locale]; const projects = preferred.map((reference) => caseStudies.find((item) => item.slug === reference || item.clientName.toLowerCase().includes(reference))).filter((item): item is CaseStudy => Boolean(item));
  const metrics = locale === "pt" ? [["1K → 13,5K", "Seguidores no Instagram"], ["460 mil+", "Pessoas alcançadas"], ["4.275", "Cliques em ligações"]] : [["1K → 13.5K", "Instagram followers"], ["460K+", "People reached"], ["4,275", "Link clicks"]];
  const headerGridImages = getPublicImageList(imageFolders.photoGallery, { text: photoGalleryImageText }).slice(0, 4);
  return <article className="overflow-hidden bg-white text-ink">
    <header className="sticky top-0 z-40 border-b border-white/15 bg-ink/95 px-5 py-4 text-white backdrop-blur sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-6"><a href="#top" className="flex items-center gap-3 font-serif text-lg tracking-[-0.03em] text-white"><span className="relative size-9 shrink-0 overflow-hidden rounded-full border border-yellow/70"><Image src="/images/tiago-bastos-headshot.png" alt="Tiago Bastos" fill sizes="36px" quality={90} className="object-cover object-center" /></span>TIAGO BASTOS</a><nav aria-label="Personal navigation" className="hidden items-center gap-5 text-[0.62rem] font-black uppercase tracking-[.14em] text-white/65 md:flex">{[["work", locale === "pt" ? "Projetos" : "Work"], ["experience", locale === "pt" ? "Experiência" : "Experience"], ["skills", locale === "pt" ? "Competências" : "Skills"], ["about", t.about], ["contact", locale === "pt" ? "Contacto" : "Contact"]].map(([id, name]) => <a key={id} href={`#${id}`} className="transition hover:text-yellow">{name}</a>)}</nav><a href="/documents/Tiago-Bastos-CV.pdf" download className="inline-flex items-center gap-2 text-[.62rem] font-black uppercase tracking-[.14em] text-yellow transition hover:text-white"><Download size={14} />{t.cv}</a></div></header>
    <section id="top" className="bg-ink px-5 py-14 text-white sm:px-8 sm:py-20"><div className="mx-auto grid max-w-7xl items-center gap-10 lg:grid-cols-[1.2fr_.8fr] lg:gap-16"><div><p className="section-eyebrow text-yellow">{t.eyebrow}</p><h1 className="mt-5 font-serif text-[clamp(3.6rem,7vw,6.6rem)] font-semibold leading-[.88] tracking-[-.05em]">Tiago<br />Bastos</h1><p className="mt-7 max-w-2xl text-xl leading-8 text-white/86 sm:text-2xl sm:leading-9">{t.subhead}</p><p className="mt-5 max-w-2xl text-base leading-8 text-white/64">{t.body}</p><div className="mt-7 flex flex-wrap gap-x-5 gap-y-3 text-xs font-bold uppercase tracking-[.13em] text-white/65"><span className="inline-flex items-center gap-2"><MapPin size={15} className="text-yellow" />{t.location}</span><span>{t.availability}</span></div><div className="mt-9 flex flex-wrap gap-3"><a href="#work" className="button-primary group">{t.work}<ArrowUpRight size={16} className="transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5" /></a><a href="/documents/Tiago-Bastos-CV.pdf" download className="button-secondary"><Download size={16} />{t.cv}</a><a href="https://www.linkedin.com/in/tiagobastos93" className="inline-flex min-h-12 items-center gap-2 px-2 text-xs font-black uppercase tracking-[.14em] text-white/68 transition hover:text-yellow"><Linkedin size={16} />LinkedIn</a></div></div><div className="mx-auto grid w-full max-w-[32rem] grid-cols-2 gap-3 sm:gap-4">{headerGridImages.map((image, index) => <figure key={image.src} className={`relative overflow-hidden rounded-[8px] border border-white/15 bg-white/5 ${index === 0 || index === 3 ? "aspect-[4/5]" : "aspect-square"}`}><Image src={image.src} alt={image.alt} fill priority={index < 2} sizes="(min-width: 1024px) 19vw, (min-width: 640px) 38vw, 43vw" className="object-cover object-center" /></figure>)}</div></div></section>
    <section id="about" className="px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto grid max-w-7xl gap-8 lg:grid-cols-[.95fr_1.05fr] lg:gap-16"><div><p className="section-eyebrow text-ink/52">{t.about}</p><h2 className="mt-4 font-serif text-[clamp(2.65rem,4.8vw,4.6rem)] leading-[.92] tracking-[-.04em]">{t.aboutTitle}</h2></div><div className="self-end"><p className="text-base leading-8 text-ink/72 sm:text-lg">{t.aboutBody}</p><p className="mt-6 border-l-2 border-yellow pl-5 text-sm leading-7 text-ink/66">{t.hospo}</p></div></div></section>
    <section id="work" className="bg-[#f5f7fa] px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-ink/52">{t.selected}</p><h2 className="mt-4 max-w-3xl font-serif text-[clamp(2.65rem,4.8vw,4.6rem)] leading-[.92] tracking-[-.04em]">{t.selectedTitle}</h2><p className="mt-5 max-w-2xl text-base leading-7 text-ink/65">{t.selectedBody}</p><div className="mt-11 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{projects.map((project) => { const item = (details[project.slug] || (project.clientName.toLowerCase().includes("pan pacific") ? details["pan-pacific-hanoi"] : undefined))?.[locale]; const image = project.heroImage || project.media?.find((media) => media.mediaType === "image")?.src; const href = localizedPath(`/case-studies/${project.slug}`, locale); return <article key={project.slug} className="group overflow-hidden rounded-[8px] border border-ink/15 bg-white transition duration-300 hover:-translate-y-1 hover:shadow-xl"><Link href={href} className="relative block aspect-[4/3] bg-ink">{image ? <Image src={image} alt={project.heroImageAlt || project.title} fill sizes="(min-width: 1280px) 29vw, (min-width: 768px) 45vw, 100vw" className="object-cover transition duration-700 group-hover:scale-[1.035]" /> : <span className="absolute inset-0 grid place-items-center p-6 text-center font-serif text-3xl text-white">{project.clientName}</span>}</Link><div className="p-6"><p className="text-[.62rem] font-black uppercase tracking-[.15em] text-ink/50">{project.clientName}{project.location ? ` · ${project.location}` : ""}</p><h3 className="mt-3 font-serif text-3xl leading-none">{project.title}</h3><p className="mt-4 text-sm font-bold leading-6 text-ink/75">{t.contribution}: {item?.[0] || project.services.slice(0, 3).join(" · ")}</p><p className="mt-3 text-sm leading-7 text-ink/64">{item?.[1] || project.summary}</p><Link href={href} className="mt-6 inline-flex items-center gap-2 text-xs font-black uppercase tracking-[.14em] text-ink transition hover:text-yellow">{t.view}<ArrowUpRight size={16} /></Link></div></article>; })}</div></div></section>
    <section className="px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-ink/52">{t.capabilities}</p><h2 className="mt-4 max-w-3xl font-serif text-[clamp(2.65rem,4.8vw,4.6rem)] leading-[.92] tracking-[-.04em]">{t.capabilitiesTitle}</h2><div className="mt-11 grid border-l border-t border-ink/15 md:grid-cols-2 lg:grid-cols-3">{capability[locale].map(([number, title, body]) => <article key={number} className="min-h-60 border-b border-r border-ink/15 p-6 sm:p-7"><p className="section-eyebrow text-ink/43">{number}</p><h3 className="mt-8 font-serif text-3xl leading-none">{title}</h3><p className="mt-4 text-sm leading-7 text-ink/65">{body}</p></article>)}</div></div></section>
    <section className="bg-ink px-5 py-[var(--hc-section-compact)] text-white sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-yellow">{t.process}</p><h2 className="mt-4 max-w-3xl font-serif text-[clamp(2.65rem,4.8vw,4.6rem)] leading-[.92] tracking-[-.04em]">{t.processTitle}</h2><div className="mt-11 grid border-l border-t border-white/15 md:grid-cols-2 lg:grid-cols-4">{production[locale].map(([number, title, body]) => <article key={number} className="min-h-56 border-b border-r border-white/15 p-6"><p className="section-eyebrow text-yellow">{number}</p><h3 className="mt-8 font-serif text-3xl">{title}</h3><p className="mt-4 text-sm leading-7 text-white/68">{body}</p></article>)}</div></div></section>
    <section className="bg-yellow px-5 py-[var(--hc-section-compact)] text-ink sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><div><p className="section-eyebrow text-ink/65">{t.results}</p><h2 className="mt-4 font-serif text-[clamp(2.65rem,4.8vw,4.6rem)] leading-[.92] tracking-[-.04em]">{t.resultsTitle}</h2></div><div><div className="grid gap-3 sm:grid-cols-3">{metrics.map(([value, label]) => <div key={value} className="border-t-2 border-ink pt-4"><p className="font-serif text-5xl leading-none">{value}</p><p className="mt-3 text-[.62rem] font-black uppercase tracking-[.14em] text-ink/65">{label}</p></div>)}</div><p className="mt-8 text-base leading-8 text-ink/75">{t.resultsBody}</p></div></div></section>
    <section id="experience" className="px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><div><p className="section-eyebrow text-ink/52">{t.experience}</p><h2 className="mt-4 font-serif text-[clamp(2.65rem,4.8vw,4.6rem)] leading-[.92] tracking-[-.04em]">{t.experienceTitle}</h2></div><div className="divide-y divide-ink/15 border-y border-ink/15">{work[locale].map(([period, company, role, body]) => <article key={`${period}-${company}`} className="grid gap-2 py-6 sm:grid-cols-[8rem_1fr] sm:gap-7"><p className="text-xs font-black uppercase tracking-[.13em] text-ink/48">{period}</p><div><h3 className="font-serif text-2xl leading-tight">{company}</h3><p className="mt-1 text-sm font-extrabold leading-6 text-ink/78">{role}</p><p className="mt-3 text-sm leading-7 text-ink/65">{body}</p></div></article>)}</div></div></section>
    <section id="skills" className="bg-[#f5f7fa] px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-ink/52">{t.skills}</p><h2 className="mt-4 max-w-3xl font-serif text-[clamp(2.65rem,4.8vw,4.6rem)] leading-[.92] tracking-[-.04em]">{t.skillsTitle}</h2><div className="mt-11 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{skills[locale].map(([category, items]) => <section key={category} className="rounded-[8px] border border-ink/15 bg-white p-6"><h3 className="font-serif text-3xl">{category}</h3><ul className="mt-5 space-y-2.5">{items.map((item) => <li key={item} className="flex gap-2.5 text-sm leading-6 text-ink/72"><Check size={16} className="mt-0.5 shrink-0 text-yellow" />{item}</li>)}</ul></section>)}</div><div className="mt-12 grid gap-8 border-t border-ink/15 pt-9 lg:grid-cols-[.8fr_1.2fr]"><p className="section-eyebrow text-ink/52">{t.development}</p><div className="divide-y divide-ink/15 border-y border-ink/15">{courses.map((item) => <p key={item} className="py-3.5 text-sm leading-6 text-ink/68">{item}</p>)}</div></div></div></section>
    <section className="bg-white px-5 py-[var(--hc-section-compact)] sm:px-8"><div className="mx-auto max-w-7xl"><p className="section-eyebrow text-ink/52">{t.testimonials}</p><h2 className="mt-4 max-w-3xl font-serif text-[clamp(2.65rem,4.8vw,4.6rem)] leading-[.92] tracking-[-.04em]">{t.testimonialsTitle}</h2><div className="mt-11 grid gap-5 lg:grid-cols-3">{feedback[locale].map(([quote, source]) => <figure key={quote} className="flex flex-col rounded-[8px] bg-ink p-6 text-white sm:p-7"><blockquote className="font-serif text-2xl leading-tight text-white">“{quote}”</blockquote><figcaption className="mt-8 border-t border-white/15 pt-4 text-[.65rem] font-black uppercase leading-5 tracking-[.13em] text-yellow">{source}</figcaption></figure>)}</div></div></section>
    <section id="contact" className="bg-yellow px-5 py-16 text-ink sm:px-8 sm:py-20"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-9 md:flex-row md:items-end"><div><p className="section-eyebrow text-ink/65">{t.connect}</p><h2 className="mt-4 max-w-4xl font-serif text-[clamp(2.8rem,5.4vw,5.2rem)] leading-[.89] tracking-[-.045em]">{t.connectTitle}</h2><p className="mt-6 max-w-2xl text-base leading-8 text-ink/75">{t.connectBody}</p></div><div className="flex flex-col gap-3 sm:flex-row md:flex-col"><a href="mailto:tiagobastosavr@gmail.com" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full bg-ink px-6 text-xs font-black uppercase tracking-[.14em] text-white transition hover:-translate-y-0.5 hover:bg-white hover:text-ink"><Mail size={16} />{t.email}</a><a href="https://www.linkedin.com/in/tiagobastos93" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-ink/45 px-6 text-xs font-black uppercase tracking-[.14em] transition hover:-translate-y-0.5"><Linkedin size={16} />LinkedIn</a><a href="/documents/Tiago-Bastos-CV.pdf" download className="inline-flex min-h-12 items-center justify-center gap-2 rounded-full border border-ink/45 px-6 text-xs font-black uppercase tracking-[.14em] transition hover:-translate-y-0.5"><Download size={16} />{t.cv}</a></div></div></section>
    <footer className="bg-ink px-5 py-7 text-white/55 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-[.65rem] font-black uppercase tracking-[.14em] sm:flex-row"><p>Tiago Bastos · Content · Photo · Video</p><p>Portugal · UK · International</p></div></footer>
  </article>;
}
