import Link from "next/link";
import { createSupabaseServerClient } from "@/lib/supabase/server";

type Prospect = { id: string; name: string; pipeline_status: string; priority: string; next_followup_at: string; primary_service: string | null; contacts: { name: string; is_primary: boolean }[] };
const date = (value: string) => new Intl.DateTimeFormat("en-GB", { day: "numeric", month: "short", year: "numeric" }).format(new Date(value));

export default async function FollowUpsPage() {
  const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("prospects").select("id,name,pipeline_status,priority,next_followup_at,primary_service,contacts:prospect_contacts(name,is_primary)").not("next_followup_at", "is", null).not("pipeline_status", "in", '("Won","Lost","Paused")').order("next_followup_at"); const prospects = (data ?? []) as unknown as Prospect[]; const today = new Date(); today.setHours(0, 0, 0, 0); const tomorrow = new Date(today); tomorrow.setDate(tomorrow.getDate() + 1); const groups = [["Overdue", prospects.filter((item) => new Date(item.next_followup_at) < today)], ["Today", prospects.filter((item) => new Date(item.next_followup_at) >= today && new Date(item.next_followup_at) < tomorrow)], ["Upcoming", prospects.filter((item) => new Date(item.next_followup_at) >= tomorrow)]] as const;
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="section-eyebrow text-ink/55">Prospecting</p><h1 className="mt-3 font-serif text-5xl font-semibold leading-none">Follow-ups.</h1></div><Link href="/admin/prospects/pipeline" className="text-xs font-black uppercase tracking-[0.14em] text-ink/60 hover:text-yellow">Open pipeline</Link></div>{error ? <p className="mt-6 rounded-[8px] border border-red-200 bg-red-50 p-4 font-bold text-red-800">{error.message}</p> : null}<div className="mt-7 grid gap-6 xl:grid-cols-3">{groups.map(([title, items]) => <section key={title} className="rounded-[8px] bg-white p-5 shadow-soft"><div className="flex items-center justify-between border-b border-ink/10 pb-4"><h2 className="font-serif text-3xl font-semibold">{title}</h2><span className="rounded-full bg-ink px-3 py-1 text-xs font-black text-white">{items.length}</span></div><div className="mt-4 space-y-3">{items.map((item) => { const primary = item.contacts?.find((contact) => contact.is_primary) ?? item.contacts?.[0]; return <Link key={item.id} href={`/admin/prospects/${item.id}`} className="block rounded-[8px] border border-ink/10 p-4 transition hover:border-yellow hover:bg-yellow/10"><div className="flex items-start justify-between gap-3"><h3 className="font-bold">{item.name}</h3><span className="text-xs font-black">{item.priority}</span></div><p className="mt-2 text-sm text-ink/65">{primary?.name || "No contact"}</p><p className="mt-1 text-xs text-ink/52">{item.pipeline_status} · {date(item.next_followup_at)}</p><p className="mt-3 text-xs font-bold text-ink/70">{item.primary_service || "Next action not specified"}</p></Link>})}{!items.length ? <p className="py-8 text-center text-sm font-bold text-ink/48">Nothing here.</p> : null}</div></section>)}</div></div>;
}
