import { CommercialItemForm } from "@/components/admin/CommercialItemForm";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import type { CommercialItem } from "@/types/commercial";
import { createAddonAction, createPackageAction, duplicatePackageAction, saveAddonMarketValueAction, savePackageMarketValueAction, updateAddonAction, updatePackageAction } from "./actions";

type AdminItem = CommercialItem & { excluded_items: string[]; excluded_items_pt: string[]; commercial_terms: string | null; commercial_terms_pt: string | null; badge: string | null; badge_pt: string | null; featured: boolean };

export default async function CommercialAdminPage() {
  const supabase = await createSupabaseServerClient();
  const [{ data: packageRows }, { data: addonRows }, { data: valueRows }, { data: addonValueRows }] = await Promise.all([
    supabase.from("packages").select("*").order("market").order("category").order("sort_order"),
    supabase.from("addons").select("*").order("market").order("category").order("sort_order"),
    supabase.from("package_market_values").select("package_id,market_code,price_amount,price_type,description,deliverables,excluded_items,production_duration,minimum_commitment,cta_label,cta_destination,is_active"),
    supabase.from("addon_market_values").select("addon_id,market_code,price_amount,price_type,description,is_active"),
  ]);
  const packages = (packageRows ?? []) as AdminItem[];
  const addons = (addonRows ?? []) as AdminItem[];
  const values = valueRows ?? [];
  const addonValues = addonValueRows ?? [];
  const marketForm = (item: AdminItem, market: "pt" | "uk") => {
    const current = values.find((value) => value.package_id === item.id && value.market_code === market);
    return <form action={savePackageMarketValueAction} className="grid gap-3 rounded-[6px] border border-ink/10 p-4"><input type="hidden" name="package_id" value={item.id}/><input type="hidden" name="market_code" value={market}/><p className="font-bold">{market === "pt" ? "Portugal · EUR" : "United Kingdom · GBP"}</p><label className="text-xs font-bold">Price<input name="price_amount" type="number" step="0.01" defaultValue={current?.price_amount ?? ""} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label><label className="text-xs font-bold">Price type<select name="price_type" defaultValue={current?.price_type ?? "monthly"} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"><option value="monthly">Monthly</option><option value="from_monthly">From monthly</option><option value="project">Project</option><option value="from_project">From project</option><option value="custom">Custom</option></select></label><label className="text-xs font-bold">{market === "pt" ? "Descrição em português" : "English description"}<textarea name="description" defaultValue={current?.description ?? ""} rows={3} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label><label className="text-xs font-bold">Deliverables, one per line<textarea name="deliverables" defaultValue={(current?.deliverables ?? []).join("\n")} rows={5} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label><label className="text-xs font-bold">Excluded services, one per line<textarea name="excluded_items" defaultValue={(current?.excluded_items ?? []).join("\n")} rows={3} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Production duration<input name="production_duration" defaultValue={current?.production_duration ?? ""} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label><label className="text-xs font-bold">Minimum commitment<input name="minimum_commitment" defaultValue={current?.minimum_commitment ?? ""} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">CTA label<input name="cta_label" defaultValue={current?.cta_label ?? ""} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label><label className="text-xs font-bold">CTA destination<input name="cta_destination" defaultValue={current?.cta_destination ?? ""} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label></div><label className="text-xs font-bold"><input type="checkbox" name="is_active" defaultChecked={current?.is_active ?? true}/> Active in this market</label><button className="justify-self-start rounded-full bg-ink px-4 py-2 text-xs font-black uppercase tracking-[0.12em] text-white">Save {market.toUpperCase()}</button></form>;
  };
  const addonMarketForm = (item: AdminItem, market: "pt" | "uk") => {
    const current = addonValues.find((value) => value.addon_id === item.id && value.market_code === market);
    return <form action={saveAddonMarketValueAction} className="grid gap-3 rounded-[6px] border border-ink/10 p-4"><input type="hidden" name="addon_id" value={item.id}/><input type="hidden" name="market_code" value={market}/><p className="font-bold">{market === "pt" ? "Portugal · EUR" : "United Kingdom · GBP"}</p><label className="text-xs font-bold">Price<input name="price_amount" type="number" step="0.01" defaultValue={current?.price_amount ?? ""} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label><label className="text-xs font-bold">Price type<select name="price_type" defaultValue={current?.price_type ?? "from_project"} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"><option value="monthly">Monthly</option><option value="from_monthly">From monthly</option><option value="project">Project</option><option value="from_project">From project</option><option value="custom">Custom</option></select></label><label className="text-xs font-bold">{market === "pt" ? "Descrição em português" : "English description"}<textarea name="description" defaultValue={current?.description ?? ""} rows={2} className="mt-1 w-full rounded border border-ink/15 px-3 py-2"/></label><label className="text-xs font-bold"><input type="checkbox" name="is_active" defaultChecked={current?.is_active ?? true}/> Active in this market</label><button className="justify-self-start rounded-full bg-ink px-4 py-2 text-xs font-black uppercase tracking-[0.12em] text-white">Save {market.toUpperCase()}</button></form>;
  };
  return <div>
    <p className="section-eyebrow text-ink/55">Commercial library</p><h1 className="mt-3 font-serif text-5xl font-semibold leading-none">Packages & add-ons.</h1>
    <p className="mt-5 max-w-3xl text-lg leading-8 text-ink/70">Current commercial templates. Changes here affect future selections only. Proposal snapshots preserve the version sent to each client.</p><div className="mt-5 flex flex-wrap gap-3"><a href="/packages" target="_blank" className="rounded-full border border-ink/20 px-4 py-2 text-xs font-black uppercase tracking-[0.12em]">Preview UK packages</a><a href="/pt/packages" target="_blank" className="rounded-full border border-ink/20 px-4 py-2 text-xs font-black uppercase tracking-[0.12em]">Preview Portugal packages</a></div>
    <section className="mt-10 rounded-[8px] bg-white p-6 shadow-soft"><p className="section-eyebrow text-ink/55">Generic landing pages</p><h2 className="mt-3 font-serif text-4xl">Portugal and UK values.</h2><p className="mt-3 max-w-3xl text-ink/65">One package identity with independent country values. Updating Portugal never changes United Kingdom pricing.</p>{(["marketing", "content_creation"] as const).map((category) => <div key={category} className="mt-8"><h3 className="font-serif text-2xl">{category === "marketing" ? "Marketing Packages" : "Content Creation Packages"}</h3><div className="mt-4 space-y-4">{packages.filter((item) => item.market === "general" && (item.category ?? "marketing") === category).map((item) => <details key={item.id} className="rounded-[6px] border border-ink/10 p-4"><summary className="cursor-pointer font-bold">{item.name}</summary><div className="mt-4 grid gap-4 lg:grid-cols-2">{marketForm(item, "pt")}{marketForm(item, "uk")}</div></details>)}</div></div>)}</section>
    <section className="mt-10 grid gap-8 xl:grid-cols-[minmax(0,1fr)_24rem]"><div className="space-y-4">{packages.map((item) => <details key={item.id} className="rounded-[8px] bg-white p-5 shadow-soft"><summary className="cursor-pointer list-none"><div className="flex items-center justify-between gap-4"><div><p className="font-bold">{item.name} <span className="font-normal text-ink/50">{item.market}</span></p><p className="mt-1 text-sm text-ink/60">{item.is_active ? "Active" : "Inactive"}{item.featured ? " · Featured" : ""}</p></div><span className="text-sm text-ink/55">Edit</span></div></summary><div className="mt-5 border-t border-ink/10 pt-5"><CommercialItemForm action={updatePackageAction} item={item} /><form action={duplicatePackageAction} className="mt-4"><input type="hidden" name="id" value={item.id}/><button className="text-sm font-bold underline">Duplicate as inactive draft</button></form></div></details>)}</div><aside className="rounded-[8px] bg-white p-5 shadow-soft"><h2 className="font-serif text-3xl">New package</h2><div className="mt-5"><CommercialItemForm action={createPackageAction} submitLabel="Create package" /></div></aside></section>
    <section className="mt-14 border-t border-ink/10 pt-10"><p className="section-eyebrow text-ink/55">Optional services</p><h2 className="mt-3 font-serif text-4xl font-semibold">Add-ons.</h2><div className="mt-7 grid gap-8 xl:grid-cols-[minmax(0,1fr)_24rem]"><div className="space-y-4">{addons.map((item) => <details key={item.id} className="rounded-[8px] bg-white p-5 shadow-soft"><summary className="cursor-pointer list-none"><p className="font-bold">{item.name} <span className="font-normal text-ink/50">{item.market}</span></p></summary><div className="mt-5 border-t border-ink/10 pt-5"><CommercialItemForm action={updateAddonAction} item={item} kind="addon" />{item.market === "general" ? <div className="mt-6 grid gap-4 lg:grid-cols-2">{addonMarketForm(item, "pt")}{addonMarketForm(item, "uk")}</div> : null}</div></details>)}</div><aside className="rounded-[8px] bg-white p-5 shadow-soft"><h3 className="font-serif text-3xl">New add-on</h3><div className="mt-5"><CommercialItemForm action={createAddonAction} kind="addon" submitLabel="Create add-on" /></div></aside></div></section>
  </div>;
}
