insert into public.packages (slug, name, market, featured, badge, badge_pt, is_active, sort_order) values
  ('content-partner', 'Content Partner', 'general', false, null, null, true, 10),
  ('presence-content', 'Presence & Content', 'general', true, 'Most popular', 'Mais procurado', true, 20),
  ('growth-bookings', 'Growth & Bookings', 'general', false, null, null, true, 30)
on conflict (slug) do nothing;

insert into public.package_market_values (package_id, market_code, currency, price_amount, price_type, description, deliverables)
select id, 'pt', 'EUR', case slug when 'content-partner' then 650 when 'presence-content' then 950 else 1350 end, 'monthly',
  case slug when 'content-partner' then 'Para negócios de hotelaria e restauração que gerem os próprios canais, mas precisam de conteúdo profissional consistente.' when 'presence-content' then 'Para marcas de hospitality que querem combinar produção profissional de conteúdo com uma presença digital consistente.' else 'Para negócios que querem ligar conteúdo, visibilidade e aquisição de clientes numa estratégia mais completa.' end,
  case slug when 'content-partner' then array['Planeamento mensal de conteúdo', 'Uma sessão mensal de produção, aproximadamente 3 horas', '20–25 fotografias editadas profissionalmente', '4 vídeos verticais de curta duração', 'Comida, bebidas, interiores, quartos, pessoas, serviço ou experiências conforme o negócio', 'Lista criativa de captações', 'Edição profissional e correção de cor', 'Biblioteca mensal de conteúdos organizada'] when 'presence-content' then array['Estratégia mensal e planeamento de conteúdos', 'Produção mensal de conteúdo profissional', 'Fotografia profissional', '4 vídeos verticais de curta duração', 'Conteúdo adicional para redes sociais', 'Gestão de Instagram e Facebook', 'Copywriting, calendário, agendamento e publicação', 'Stories planeadas, gestão de comunidade leve e revisão mensal'] else array['Tudo do Presence & Content', 'Capacidade adicional de vídeo de curta duração', 'Gestão de media pago', 'Meta e/ou Google conforme a estratégia e âmbito acordado', 'Otimização do Perfil de Empresa no Google', 'Visibilidade local e estratégia de reputação', 'Planeamento de campanhas e recomendações para website ou reservas', 'Relatório de desempenho comercial e chamada mensal de estratégia'] end
from public.packages where slug in ('content-partner','presence-content','growth-bookings')
on conflict (package_id, market_code) do nothing;

insert into public.package_market_values (package_id, market_code, currency, price_amount, price_type, description, deliverables)
select id, 'uk', 'GBP', case slug when 'content-partner' then 850 when 'presence-content' then 1250 else 1750 end, 'monthly',
  case slug when 'content-partner' then 'For hospitality businesses that manage their own channels but need a reliable stream of professional content.' when 'presence-content' then 'For hospitality brands that want professional content combined with consistent management of their digital presence.' else 'For businesses ready to connect content, visibility and customer acquisition in one more complete strategy.' end,
  case slug when 'content-partner' then array['Monthly content planning', 'One monthly production session, approximately 3 hours', '20–25 professionally edited photographs', '4 short-form vertical videos', 'Food, drinks, interiors, rooms, people, service or experiences depending on the business', 'Creative shot list', 'Professional editing and colour grading', 'Organised monthly content library'] when 'presence-content' then array['Monthly strategy and content planning', 'Monthly professional content production', 'Professional photography', '4 short-form vertical videos', 'Additional social content', 'Instagram and Facebook management', 'Copywriting, content calendar, scheduling and publishing', 'Planned Stories, light community management and monthly performance review'] else array['Everything in Presence & Content', 'Additional short-form video capacity', 'Paid media management', 'Meta and/or Google depending on agreed strategy and scope', 'Google Business Profile optimisation', 'Local visibility and review strategy', 'Campaign planning and website or booking journey recommendations', 'Commercial performance reporting and monthly strategy call'] end
from public.packages where slug in ('content-partner','presence-content','growth-bookings')
on conflict (package_id, market_code) do nothing;
