import { notFound } from "next/navigation";
import { Check } from "lucide-react";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
import { PublicProposalTracker } from "@/components/PublicProposalTracker";
import { getRequestLocale } from "@/lib/locale-server";
import { createSupabasePublicClient } from "@/lib/supabase/public";
import type { PublicProposal } from "@/types/commercial";

export const dynamic = "force-dynamic";
export const metadata = { robots: { index: false, follow: false } };

export default async function PublicProposalPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const locale = await getRequestLocale(); const supabase = createSupabasePublicClient(); const { data, error } = await supabase.rpc("get_sent_proposal", { p_slug: slug }); if (error || !data) notFound(); const proposal = data as PublicProposal; const snapshot = proposal.package_snapshot as { name?: string; name_pt?: string; description?: string; description_pt?: string; included_items?: string[]; included_items_pt?: string[] } | null; const name = locale === "pt" ? proposal.business_name || proposal.client_name || "Proposta" : proposal.business_name || proposal.client_name || "Proposal"; const packageName = locale === "pt" ? snapshot?.name_pt || snapshot?.name : snapshot?.name; const included = locale === "pt" ? snapshot?.included_items_pt || snapshot?.included_items : snapshot?.included_items; const cta = proposal.cta_config?.url; return <><Header locale={locale}/><main><section className="bg-ink pb-24 pt-32 text-white"><div className="page-shell"><p className="section-eyebrow text-yellow">{locale === "pt" ? "Proposta preparada para" : "Proposal prepared for"}</p><h1 className="mt-4 max-w-4xl font-serif text-6xl leading-none">{name}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/72">{proposal.introduction || (locale === "pt" ? "Uma proposta comercial preparada pela Hospo Creative." : "A commercial proposal prepared by Hospo Creative.")}</p><div className="mt-9"><PublicProposalTracker slug={proposal.slug} ctaUrl={typeof cta === "string" ? cta : undefined} ctaLabel={typeof proposal.cta_config?.label === "string" ? proposal.cta_config.label : undefined}/></div></div></section><section className="section-pad"><div className="page-shell grid gap-10 lg:grid-cols-[1fr_0.9fr]"><div><p className="section-eyebrow text-ink/55">{locale === "pt" ? "A oportunidade" : "The opportunity"}</p><h2 className="mt-3 font-serif text-5xl">{proposal.headline || (locale === "pt" ? "Um plano ligado ao que importa agora." : "A plan connected to what matters now.")}</h2>{proposal.personal_message ? <p className="mt-6 max-w-2xl text-lg leading-8 text-ink/70">{proposal.personal_message}</p> : null}</div><div className="rounded-[8px] bg-sand p-7"><p className="section-eyebrow text-ink/55">{locale === "pt" ? "Package recomendado" : "Recommended package"}</p><h2 className="mt-3 font-serif text-4xl">{packageName || (locale === "pt" ? "Proposta personalizada" : "Custom proposal")}</h2><p className="mt-4 leading-7 text-ink/70">{locale === "pt" ? snapshot?.description_pt || snapshot?.description : snapshot?.description}</p><ul className="mt-6 space-y-3">{(included ?? []).map((item) => <li key={item} className="flex gap-3 text-sm leading-6"><Check size={17} className="mt-0.5 shrink-0 text-yellow"/>{item}</li>)}</ul></div></div></section></main><Footer locale={locale}/></>; }
